#!/bin/bash

# Copyright (c) 2025, Matthew Ricci
# Copyright (c) 2017-2025, Medicine Yeh
# MIT License

function replace_all()
{
    IFS=', ' read -r -a _prefixes <<< "$1"
    local pattern="$2"
    local file_pathes=("${!3}")

    for file_path in "${file_pathes[@]}"; do
        [[ ! -r "$file_path" ]] && continue
        for prefix in "${_prefixes[@]}"; do
            # echo "s/${prefix}/${pattern}${prefix}/g"
            sed -i "s/${prefix}/${pattern}${prefix}/g" "${file_path}"
        done
    done
}

function re_replace_all()
{
    IFS=', ' read -r -a _prefixes <<< "$1"
    local pattern="$2"
    local file_pathes=("${!3}")

    for file_path in "${file_pathes[@]}"; do
        [[ ! -r "$file_path" ]] && continue
        for prefix in "${_prefixes[@]}"; do
            # echo "s/${pattern}${prefix}/${prefix}/g"
            sed -i "s/${pattern}${prefix}/${prefix}/g" "${file_path}"
        done
    done
}

function format()
{
    clang-format "$@"
}

function main()
{
    # This is the pattern for replacing to comments
    local comment_pattern="\/\/"

    # This is the pattern for replacing comments back to original string
    local re_comment_pattern="\/\/* *"

    # The path of files
    local file_pathes=()

    # Define the keywords of pragma to be escaped from formatting
    local prefixes="#pragma #define #if #else #end"

    # Find all files in the arguments
    for var in "$@"; do
        if [[ ! "$var" =~ ^-.* ]]; then
            file_pathes+=("$var")
        fi
    done

    # Replace all prefixes "#prefix" -> "//#prefix"
    replace_all "$prefixes" "$comment_pattern" "file_pathes[@]"

    # Run clang-format and 
    format "$@"

    # Replace all prefixes "//#prefix" -> "#prefix"
    re_replace_all "$prefixes" "$re_comment_pattern" "file_pathes[@]"
}

main "$@"
